// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: item.proto

/*
Package http is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	item.proto
*/
package http

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathItemGetList = "/item/list"

// ItemBMServer is the server API for Item service.
type ItemBMServer interface {
	// `internal:"true"` 获取商品列表
	GetList(ctx context.Context, req *ItemGetListReq) (resp *ItemGetListResp, err error)
}

var ItemSvc ItemBMServer

func itemGetList(c *bm.Context) {
	p := new(ItemGetListReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ItemSvc.GetList(c, p)
	c.JSON(resp, err)
}

// RegisterItemBMServer Register the blademaster route
func RegisterItemBMServer(e *bm.Engine, server ItemBMServer) {
	ItemSvc = server
	e.GET("/item/list", itemGetList)
}
